### ISSUE TITLE
Avoid reloading FMU for simulation

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/MPCPy#126]
This issue is to correct using the ``pyfmi.load_fmu()`` function when simulating an fmu, instead relying on the function only once in ``utility._fmu._create_fmu()``.  As is, reloading the fmu during the  ``utility._fmu._simulate_fmu()`` call changes the pointer of the pyfmi fmu object in a way that can cause errors in simulating co-simulation FMUs.

@tsnouidui Is this accurate?

**Comment by dhblum** [comment]
I just pushed a branch (issue126_reloadFMU) for this using ``fmu.reset()``.  See if this works for you?

**Comment by tsnouidui** [comment]
Yes. That works. Thanks!

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/MPCPy/pull/129/
