### ISSUE TITLE
Method for retrieving weather forecasts

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/MPCPy#161]
This issue is to implement a method for forecasting solar radiation.

**Comment by dhblum** [comment]
This issue will implement a method of getting weather forecasts from a service.  To start, the service should be NOAA.  In addition, global horizontal solar irradiation should be generated from sky clearness forecasts using the Zhang-Huang model (used in E+ aux program to create new weather files if no solar irradiation available).

**Comment by WalterZWang** [comment]
Hi @dhblum,

I added a class WeatherFromNOAA, which calls WeatherFromDF to complete the function. Please review and let me know if you have any questions.

**Comment by WalterZWang** [comment]
Hey @dhblum, I have implemented the weather forecast function, and think it is ready for your review.
Best and have a great weekend, Zhe

**Comment by WalterZWang** [comment]
Hey @dhblum, I think all your comments have been addressed. I ran the unittest again and passed it.

When I rerun the unit test, I found the NOAA API does not allow us to access all historical data, rather it allows up to 4 weeks of historical weather data. Therefore, I re-implement the unittest for historical weather data in a similar way to the unittest of weather forecast data, i.e. check the value range and length of data.

Please review and let me know if you have any further comments.

**Comment by WalterZWang** [comment]
Hey @dhblum, I think the time zone has been fixed. Could you please test it in Boston time.

Best and have a great weekend, Zhe

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/MPCPy/pull/203.
