### ISSUE TITLE
specification of package dependency

### ISSUE THREAD

**Issue by JamesCheng21** [lbl-srg/MPCPy#209]
when trying to implement MPCPy, I found a couple package dependency issues that you might want to mention in the user guide
- the latest pandas package causes some time zone error, so instead of pandas >= 0.20.3, maybe specify ==
- under ubuntu 18.04, some modification regarding pyjmi is needed, more details [here](https://stackoverflow.com/questions/55230042/jmodelica-on-ubuntu-18-04)

**Comment by dhblum** [comment]
Thanks for pointing out the pandas version typo.  I will make a change.  See also https://github.com/lbl-srg/MPCPy/issues/171.

I have not done extensive testing on Ubuntu 18.04, but the issue you bring up is very good to know.

**Comment by dhblum** [comment]
Pandas version specification issue addressed in https://github.com/lbl-srg/MPCPy/pull/210.

Updates for latest pandas version should be addressed in https://github.com/lbl-srg/MPCPy/issues/171.

A new issue has been created for updates for Ubuntu 18.04 at https://github.com/lbl-srg/MPCPy/issues/211.
